language: csharp
solution: AvalonAssets.sln
install:
  - nuget restore AvalonAssets.sln
script:
  - xbuild /p:Configuration=Release AvalonAssets.sln
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./AvalonAssetsTests/bin/Release/AvalonAssetsTests.dll